import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  mySidebar: [
    {
      type: 'category',
      label: 'General IT',
      link: {
        type: 'generated-index',
        title: 'General IT',
        description: '###',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '1_general_IT',
        },
      ],
    },
    {
      type: 'category',
      label: 'BrillianIdeas',
      link: {
        type: 'generated-index',
        title: 'BrillianIdeas',
        description: '###',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '2_brillianideas',
        },
      ],
    },
    {
      type: 'category',
      label: 'BrillianQuiz',
      link: {
        type: 'generated-index',
        title: 'BrillianQuiz',
        description: '###',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '3_brillianquiz',
        },
      ],
    },
    {
      type: 'category',
      label: 'BrillianCRM',
      link: {
        type: 'generated-index',
        title: 'BrillianCRM',
        description: '###',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '4_brilliancrm',
        },
      ],
    },
    {
      type: 'category',
      label: 'BrillianICM',
      link: {
        type: 'generated-index',
        title: 'BrillianICM',
        description: '###',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '5_brillianicm',
        },
      ],
    },
    {
      type: 'category',
      label: 'IMBIT-N3xt',
      link: {
        type: 'generated-index',
        title: 'IMBIT-N3xt',
        description: '###',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '6_imbit-n3xt',
        },
      ],
    },
    {
      type: 'category',
      label: 'BrillianDocs',
      link: {
        type: 'generated-index',
        title: 'BrillianDocs',
        description: '###',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '7_brilliandocs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Other',
      link: {
        type: 'generated-index',
        title: 'Other',
        description: '###',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '8_other',
        },
      ],
    },
  ],

//   GeneralITSidebar: [
//     {
//       type: 'category',
//       label: 'General IT',
//       link: {
//         type: 'generated-index',
//         title: 'General IT',
//         description: 'Learn about the most important Docusaurus concepts!',
//       },
//       items: [
//         {
//           type: 'autogenerated',
//           dirName: 'general_IT',
//         },
//       ],
//     },
//   ],

//   BrillianIdeasSidebar: [
//     {
//       type: 'category',
//       label: 'Brilliant Ideas',
//       items: [
//         {
//           type: 'autogenerated',
//           dirName: 'brillianideas',
//         },
//       ],
//     },
//   ],

//   BrillianQuizSidebar: [
//     {
//       type: 'category',
//       label: 'Brilliant Quiz',
//       items: [
//         {
//           type: 'autogenerated',
//           dirName: 'brillianquiz',
//         },
//       ],
//     },
//   ],

//   BrillianCRMSidebar: [
//     {
//       type: 'category',
//       label: 'Brilliant CRM',
//       items: [
//         {
//           type: 'autogenerated',
//           dirName: 'brilliancrm',
//         },
//       ],
//     },
//   ],

//   BrillianICMSidebar: [
//     {
//       type: 'category',
//       label: 'Brilliant ICM',
//       items: [
//         {
//           type: 'autogenerated',
//           dirName: 'brillianicm',
//         },
//       ],
//     },
//   ],

//   IMBITN3xtSidebar: [
//     {
//       type: 'category',
//       label: 'IMBIT N3XT',
//       items: [
//         {
//           type: 'autogenerated',
//           dirName: 'imbit-n3xt',
//         },
//       ],
//     },
  // ],
};


export default sidebars;
