import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {

  GeneralITSidebar: [
    {
      type: 'autogenerated',
      dirName: 'general_IT',
    },
  ],

  BrillianIdeasSidebar: [
    {
      type: 'autogenerated',
      dirName: 'brillianideas',
    },
  ],

  BrillianQuizSidebar: [
    {
      type: 'autogenerated',
      dirName: 'brillianquiz',
    },
  ],

  BrillianCRMSidebar: [
    {
      type: 'autogenerated',
      dirName: 'brilliancrm',
    },
  ],

  BrillianICMSidebar: [
    {
      type: 'autogenerated',
      dirName: 'brillianicm',
    },
  ],

  IMBITN3xtSidebar: [
    {
      type: 'autogenerated',
      dirName: 'imbit-n3xt',
    },
  ],
};

export default sidebars;
